version: '3.8'
services:
  postgres:
    image: postgres:alpine
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 10s
        timeout: 5s
        retries: 5
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
