version: "3.8"
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  backend:
    build: .
    restart: on-failure:2
    environment:
      DB_HOST: postgres
    ports:
      - 8080:8080
    depends_on: 
      - postgres
    command: >
      sh -c "./wait-for-it.sh postgres:5432"
